### PR TITLE
Fix and dep update

### PR DESCRIPTION
**Pull request by jezmck**

### CODE REVIEW

**Comment by jezmck** [comment]
Hi @tobievii @chriscn, I guess this is rather abandoned?

**Comment by tobievii** [comment]
Yeah it is, , these days they are integrated to google now so I don’t see a need to further dev on it

**Comment by jezmck** [comment]
Okay, I have a use for it, logging temperatures, so I'll just keep my fork going.
Thanks for creating it in the first place 😄.

**Comment by chriscn** [comment]
Personally there are better and easier to integrate smart plugs on the market. 

I've moved over to Tasmota with Home Assistant for my needs.

**Comment by chriscn** [comment]
@jezmck if you would like changes merged. Submit a PR to my repo and I'll take a look.

**Comment by jezmck** [comment]
@chriscn Yeah, agreed, but I'm using the eTRVs for this project.

**Pull request closed without merging**
